# Generated by Django 4.2.4 on 2023-10-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facultylogin',
        ),
    ]
