# Generated by Django 4.2.4 on 2023-10-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0004_studentmarks_delete_mark_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
