# Generated by Django 4.2.4 on 2023-11-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0012_delete_studentmarks'),
        ('facultyapp', '0005_delete_studentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student')),
            ],
            options={
                'db_table': 'studentmarks_table',
            },
        ),
    ]
