# Generated by Django 4.2.4 on 2023-10-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_grade_grade_remove_grade_semester_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='StudentMarks',
        ),
    ]
