# Generated by Django 4.2.4 on 2023-10-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rename_grade_studentmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='student',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='course',
            new_name='subject',
        ),
    ]
