# Generated by Django 4.2.4 on 2023-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_student_studentmarks_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='subject',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='student_name',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
