# Generated by Django 4.2.4 on 2023-10-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_studentmarks_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='studentmarksid',
            field=models.IntegerField(default=32199),
        ),
    ]
