# Generated by Django 4.2.4 on 2023-11-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_studentmarks_studentmarksid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
